name: C/C++ CI

on:
  push:
    branches: [ "default" ]
  pull_request:
    branches: [ "default" ]

jobs:
  build:

    runs-on: srivalli-VirtualBox

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: gcc Hello.c
