name: C/C++ CI

on:
  push:
    branches: [ "default" ]
  pull_request:
    branches: [ "default" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: echo "Hellooooo from self hosted runner"
